export {
  agentScope,
  appScope,
  assertCapabilityTarget,
  assertRuntimeEndpointRef,
  assertRuntimeScope,
  assertSessionIdentity,
  bootstrapScope,
  buildCapabilityScopeKey,
  buildCapabilityTargetKey,
  buildRuntimeEndpointKey,
  buildSessionIdentityKey,
  capabilityScopesEqual,
  connectorRuntimeEndpoint,
  nativeRuntimeEndpoint,
  runtimeEndpointsEqual,
  runtimeInstanceScope,
  sessionIdentitiesEqual,
  sessionScope,
  targetBelongsToScope,
  validateCapabilityTarget,
  validateRuntimeEndpointRef,
  validateRuntimeScope,
  validateSessionIdentity,
  type AgentScope,
  type AgentTarget,
  type AppScope,
  type ApprovalTarget,
  type BootstrapScope,
  type CapabilityRouteTarget,
  type CapabilityTarget,
  type CapabilityTargetKind,
  type ChannelPairingTarget,
  type ChannelTarget,
  type ConnectorRuntimeEndpointRef,
  type CronJobTarget,
  type GatewayControlTarget,
  type LicenseTarget,
  type ModelSelectionTarget,
  type NativeRuntimeEndpointRef,
  type NoCapabilityTarget,
  type PluginTarget,
  type ProviderAccountTarget,
  type ProviderCredentialTarget,
  type ProviderOAuthTarget,
  type RuntimeEndpointKind,
  type RuntimeEndpointRef,
  type RuntimeInstanceScope,
  type RuntimeJobTarget,
  type RuntimeScope,
  type RuntimeScopeKind,
  type SecurityPolicyTarget,
  type SecurityRemediationTarget,
  type SessionIdentity,
  type SessionScope,
  type SessionTarget,
  type SettingTarget,
  type SkillBundleTarget,
  type SkillTarget,
  type SubagentTarget,
  type TaskTarget,
  type TeamApprovalTarget,
  type TeamDispatchTarget,
  type TeamRunScope,
  type TeamRunTarget,
  type TeamStageTarget,
  type TeamTarget,
  type ToolTarget,
  type WorkspaceFileTarget,
  type WorkspaceScope,
  type WorkspaceStagingTarget,
} from '../../../shared/runtime-address';
