export const MAIN_API_ALLOWED_ROUTE_FILES = Object.freeze([
  'account.ts',
  'agents.ts',
  'app.ts',
  'billing.ts',
  'capabilities.ts',
  'channel-authorization.ts',
  'channel-catalog.ts',
  'channel-configure.ts',
  'channel-credentials.ts',
  'channel-delete-config.ts',
  'channel-login.ts',
  'channel-config-read.ts',
  'channel-control.ts',
  'channel-pairing.ts',
  'channel-status.ts',
  'chat-history.ts',
  'clawhub-skill.ts',
  'cron.ts',
  'diagnostics.ts',
  'fleet.ts',
  'external-connectors.ts',
  'settings-desired.ts',
  'security-policy.ts',
  'security.ts',
  'sealed-skills.ts',
  'sessions.ts',
  'settings.ts',
  'skill-bundle.ts',
  'skills.ts',
  'subscription.ts',
  'files.ts',
  'gateway.ts',
  'logs.ts',
  'runtime-host-process.ts',
  'runtime-host-usage.ts',
  'runtime-directory.ts',
  'manual-team.ts',
  'matcha-agent-app-server.ts',
  'openclaw.ts',
  'openclaw-mcp-servers.ts',
  'packages.ts',
  'plugins.ts',
  'provider-accounts.ts',
  'provider-models.ts',
  'provider-routing.ts',
  'security-emergency.ts',
  'team-approvals.ts',
  'team-decision.ts',
  'team-graph.ts',
  'team-lifecycle.ts',
  'team-public.ts',
  'team-task-board.ts',
  'toolchain.ts',
  'team-role-sessions.ts',
  'team-runtime-capability.ts',
  'team-skill.ts',
  'team-trigger.ts',
  'team-webhook-auth.ts',
  'usage.ts',
]);

export const HOSTAPI_PROXY_WEBSOCKET_EXACT_ROUTES = Object.freeze([
  '/api/remote-fleet/terminal/stream',
]);

export const MAIN_OWNED_EXACT_ROUTES = Object.freeze([
  '/api/events',
  '/api/account/public-settings',
  '/api/account/session',
  '/api/account/login',
  '/api/account/login/2fa',
  '/api/account/register',
  '/api/account/send-verify-code',
  '/api/account/refresh',
  '/api/account/logout',
  '/api/app/browser-relay-info',
  '/api/billing/checkout-info',
  '/api/billing/plans',
  '/api/billing/orders',
  '/api/billing/orders/verify',
  '/api/subagents/agents',
  '/api/capabilities/list',
  '/api/capabilities/describe',
  '/api/capabilities/execute',
  '/api/channels/authorization',
  '/api/channels/catalog',
  '/api/channels/configure',
  '/api/channels/credentials/validate',
  '/api/channels/config/validate',
  '/api/channels/delete-config',
  '/api/channels/login',
  '/api/channels/config/read',
  '/api/channels/control',
  '/api/channels/pairing',
  '/api/channels/status',
  '/api/channels/snapshot',
  '/api/clawhub/skills/install',
  '/api/clawhub/search',
  '/api/cron/jobs',
  '/api/cron/jobs/create',
  '/api/cron/jobs/update',
  '/api/cron/jobs/delete',
  '/api/cron/jobs/toggle',
  '/api/cron/session-history',
  '/api/matcha-agent/chat/history',
  '/api/usage/recent',
  '/api/diagnostics/memory',
  '/api/diagnostics/gateway-snapshot',
  '/api/diagnostics/archive',
  '/api/diagnostics/archive/download',
  '/api/settings',
  '/api/settings/desired',
  '/api/security',
  '/api/security/audit',
  '/api/security/destructive-rule-catalog',
  '/api/security/emergency',
  '/api/security/policy',
  '/api/security/policy/current',
  '/api/security/operation',
  '/api/files/save-image',
  '/api/files/binary',
  '/api/files/read-text',
  '/api/files/list-dir',
  '/api/files/write-text',
  '/api/logs',
  '/api/logs/dir',
  '/api/logs/files',
  '/api/openclaw/logs/dir',
  '/api/gateway/status',
  '/api/gateway/health',
  '/api/gateway/start',
  '/api/gateway/stop',
  '/api/gateway/restart',
  '/api/gateway/control-ui',
  '/api/openclaw/status',
  '/api/openclaw/ready',
  '/api/openclaw/dir',
  '/api/openclaw/config-dir',
  '/api/openclaw/subagent-templates',
  '/api/openclaw/workspace-dir',
  '/api/openclaw/task-workspace-dirs',
  '/api/openclaw/skills-dir',
  '/api/openclaw/cli-command',
  '/api/openclaw/tool-permission-mode',
  '/api/openclaw/runtime/snapshot',
  '/api/openclaw/lifecycle/status',
  '/api/openclaw/lifecycle/restart',
  '/api/openclaw/mcp-servers',
  '/api/openclaw/logs',
  '/api/packages/mine',
  '/api/packages/market',
  '/api/packages/upload',
  '/api/packages/download-record',
  '/api/packages/download',
  '/api/packages/install',
  '/api/runtime-host/status',
  '/api/runtime-host/restart',
  '/api/provider-accounts',
  '/api/provider-models',
  '/api/provider-models/selectable',
  '/api/provider-models/discover',
  '/api/provider-routing',
  '/api/external-connectors',
  '/api/external-connectors/mcp-server-programs',
  '/api/external-connectors/status',
  '/api/external-connectors/get',
  '/api/external-connectors/probe',
  '/api/external-connectors/session-status',
  '/api/external-connectors/upsert',
  '/api/external-connectors/remove',
  '/api/plugins/catalog',
  '/api/plugins/runtime',
  '/api/plugins/configuration',
  '/api/plugins/operation',
  '/api/skills/status',
  '/api/skills/detail',
  '/api/skills/config',
  '/api/skills/clawhub/install',
  '/api/skills/clawhub/update',
  '/api/skills/upload/begin',
  '/api/skills/upload/chunk',
  '/api/skills/upload/commit',
  '/api/skills/uninstall',
  '/api/skills/import/markdown',
  '/api/skills/import/bundle',
  '/api/skills/readme',
  '/api/sealed-skills/status',
  '/api/sealed-skills/export',
  '/api/sealed-skills/install',
  '/api/sealed-skills/uninstall',
  '/api/subagents/skill-bundles/export',
  '/api/subagents/skill-bundles/import',
  '/api/subscription/summary',
  '/api/subscription/active',
  '/api/subscription/progress',
  '/api/subscription/platform-quotas',
  '/api/matcha-agent/app-server/status',
  '/api/matcha-agent/app-server/restart',
  '/api/runtime-host/usage/recent',
  '/api/runtime-host/usage/session-timeseries',
  '/api/runtime-adapters/list',
  '/api/runtime-adapters/instances/list',
  '/api/runtime-connectors/list',
  '/api/runtime-connectors/connect',
  '/api/runtime-connectors/disconnect',
  '/api/platform/tools',
  '/api/runtime-endpoints/list',
  '/api/team/approvals',
  '/api/team/decision',
  '/api/team/role-sessions',
  '/api/team/graph',
  '/api/team/lifecycle',
  '/api/team/manual-materialize-and-create',
  '/api/team/public',
  '/api/team/skill',
  '/api/team/task-board',
  '/api/team/trigger',
  '/api/runtime-host/team-webhook-auth',
  '/api/toolchain/uv/check',
  '/api/toolchain/uv/prepare',
  '/api/remote-fleet/list-audit-events',
  '/api/remote-fleet/list-commands',
  '/api/remote-fleet/metrics',
  '/api/remote-fleet/snapshot',
  '/api/remote-fleet/terminal/sessions',
  '/api/remote-fleet/runtime-agent/ingress',
  '/api/remote-fleet/drain-endpoint',
  '/api/remote-fleet/install-agent',
  '/api/remote-fleet/probe',
  '/api/remote-fleet/probe-connection',
  '/api/remote-fleet/start-runtime',
  '/api/remote-fleet/stop-runtime',
  '/api/remote-fleet/sync-capabilities',
  '/api/remote-fleet/register-connection',
  '/api/remote-fleet/delete-connection',
  '/api/remote-fleet/register-environment',
  '/api/remote-fleet/deploy-environment',
  '/api/remote-fleet/delete-environment',
  '/api/remote-fleet/write-credential',
  '/api/remote-fleet/terminal/open',
  '/api/remote-fleet/terminal/reconnect',
  '/api/remote-fleet/terminal/close',
  '/api/remote-fleet/remove-node',
  '/api/remote-fleet/retire-endpoint',
  '/api/remote-fleet/revoke-agent',
]);

type HostApiAllowedRequest = readonly [method: string, pathname: string];

const HOST_API_ALLOWED_REQUESTS: readonly HostApiAllowedRequest[] = Object.freeze([
  ['GET', '/api/events'],
  ['GET', '/api/account/public-settings'],
  ['GET', '/api/account/session'],
  ['POST', '/api/account/login'],
  ['POST', '/api/account/login/2fa'],
  ['POST', '/api/account/register'],
  ['POST', '/api/account/send-verify-code'],
  ['POST', '/api/account/refresh'],
  ['POST', '/api/account/logout'],
  ['GET', '/api/app/browser-relay-info'],
  ['GET', '/api/billing/checkout-info'],
  ['GET', '/api/billing/plans'],
  ['POST', '/api/billing/orders'],
  ['POST', '/api/billing/orders/verify'],
  ['POST', '/api/subagents/agents'],
  ['GET', '/api/capabilities/list'],
  ['POST', '/api/capabilities/describe'],
  ['POST', '/api/capabilities/execute'],
  ['POST', '/api/channels/authorization'],
  ['POST', '/api/channels/catalog'],
  ['POST', '/api/channels/configure'],
  ['POST', '/api/channels/credentials/validate'],
  ['POST', '/api/channels/config/validate'],
  ['POST', '/api/channels/delete-config'],
  ['POST', '/api/channels/login'],
  ['POST', '/api/channels/config/read'],
  ['POST', '/api/channels/control'],
  ['POST', '/api/channels/pairing'],
  ['POST', '/api/channels/status'],
  ['GET', '/api/channels/snapshot'],
  ['POST', '/api/clawhub/skills/install'],
  ['POST', '/api/clawhub/search'],
  ['GET', '/api/cron/jobs'],
  ['POST', '/api/cron/jobs/create'],
  ['POST', '/api/cron/jobs/update'],
  ['POST', '/api/cron/jobs/delete'],
  ['POST', '/api/cron/jobs/toggle'],
  ['GET', '/api/cron/session-history'],
  ['POST', '/api/matcha-agent/chat/history'],
  ['GET', '/api/usage/recent'],
  ['GET', '/api/diagnostics/memory'],
  ['GET', '/api/diagnostics/gateway-snapshot'],
  ['POST', '/api/diagnostics/archive'],
  ['POST', '/api/diagnostics/archive/download'],
  ['GET', '/api/settings'],
  ['POST', '/api/settings/desired'],
  ['GET', '/api/security'],
  ['GET', '/api/security/audit'],
  ['GET', '/api/security/destructive-rule-catalog'],
  ['POST', '/api/security/emergency'],
  ['POST', '/api/security/policy'],
  ['GET', '/api/security/policy/current'],
  ['POST', '/api/security/operation'],
  ['POST', '/api/files/save-image'],
  ['POST', '/api/files/binary'],
  ['POST', '/api/files/read-text'],
  ['POST', '/api/files/list-dir'],
  ['POST', '/api/files/write-text'],
  ['GET', '/api/logs'],
  ['GET', '/api/logs/dir'],
  ['GET', '/api/logs/files'],
  ['GET', '/api/openclaw/logs/dir'],
  ['GET', '/api/gateway/status'],
  ['GET', '/api/gateway/health'],
  ['POST', '/api/gateway/start'],
  ['POST', '/api/gateway/stop'],
  ['POST', '/api/gateway/restart'],
  ['GET', '/api/gateway/control-ui'],
  ['GET', '/api/openclaw/status'],
  ['GET', '/api/openclaw/ready'],
  ['GET', '/api/openclaw/dir'],
  ['GET', '/api/openclaw/config-dir'],
  ['GET', '/api/openclaw/subagent-templates'],
  ['GET', '/api/openclaw/workspace-dir'],
  ['GET', '/api/openclaw/task-workspace-dirs'],
  ['GET', '/api/openclaw/skills-dir'],
  ['GET', '/api/openclaw/cli-command'],
  ['GET', '/api/openclaw/tool-permission-mode'],
  ['PUT', '/api/openclaw/tool-permission-mode'],
  ['GET', '/api/openclaw/runtime/snapshot'],
  ['GET', '/api/openclaw/lifecycle/status'],
  ['POST', '/api/openclaw/lifecycle/restart'],
  ['GET', '/api/openclaw/mcp-servers'],
  ['GET', '/api/openclaw/logs'],
  ['GET', '/api/packages/mine'],
  ['GET', '/api/packages/market'],
  ['POST', '/api/packages/upload'],
  ['POST', '/api/packages/download-record'],
  ['POST', '/api/packages/download'],
  ['POST', '/api/packages/install'],
  ['GET', '/api/provider-accounts'],
  ['GET', '/api/provider-models'],
  ['POST', '/api/provider-models'],
  ['GET', '/api/provider-models/selectable'],
  ['GET', '/api/provider-models/discover'],
  ['GET', '/api/provider-routing'],
  ['POST', '/api/provider-routing'],
  ['GET', '/api/external-connectors'],
  ['GET', '/api/external-connectors/mcp-server-programs'],
  ['GET', '/api/external-connectors/status'],
  ['POST', '/api/external-connectors'],
  ['POST', '/api/external-connectors/get'],
  ['POST', '/api/external-connectors/probe'],
  ['POST', '/api/external-connectors/session-status'],
  ['POST', '/api/external-connectors/upsert'],
  ['POST', '/api/external-connectors/remove'],
  ['GET', '/api/plugins/catalog'],
  ['GET', '/api/plugins/runtime'],
  ['POST', '/api/plugins/configuration'],
  ['POST', '/api/plugins/operation'],
  ['GET', '/api/skills/status'],
  ['POST', '/api/skills/detail'],
  ['POST', '/api/skills/config'],
  ['POST', '/api/skills/clawhub/install'],
  ['POST', '/api/skills/clawhub/update'],
  ['POST', '/api/skills/upload/begin'],
  ['POST', '/api/skills/upload/chunk'],
  ['POST', '/api/skills/upload/commit'],
  ['POST', '/api/skills/uninstall'],
  ['POST', '/api/skills/import/markdown'],
  ['POST', '/api/skills/import/bundle'],
  ['POST', '/api/skills/readme'],
  ['GET', '/api/sealed-skills/status'],
  ['POST', '/api/sealed-skills/export'],
  ['POST', '/api/sealed-skills/install'],
  ['POST', '/api/sealed-skills/uninstall'],
  ['POST', '/api/subagents/skill-bundles/export'],
  ['POST', '/api/subagents/skill-bundles/import'],
  ['GET', '/api/subscription/summary'],
  ['GET', '/api/subscription/active'],
  ['GET', '/api/subscription/progress'],
  ['GET', '/api/subscription/platform-quotas'],
  ['GET', '/api/matcha-agent/app-server/status'],
  ['POST', '/api/matcha-agent/app-server/restart'],
  ['GET', '/api/runtime-host/usage/recent'],
  ['GET', '/api/runtime-host/usage/session-timeseries'],
  ['GET', '/api/runtime-host/status'],
  ['GET', '/api/runtime-adapters/list'],
  ['GET', '/api/runtime-adapters/instances/list'],
  ['GET', '/api/runtime-connectors/list'],
  ['POST', '/api/runtime-connectors/connect'],
  ['POST', '/api/runtime-connectors/disconnect'],
  ['GET', '/api/platform/tools'],
  ['GET', '/api/runtime-endpoints/list'],
  ['POST', '/api/runtime-host/restart'],
  ['POST', '/api/team/approvals'],
  ['POST', '/api/team/decision'],
  ['POST', '/api/team/role-sessions'],
  ['POST', '/api/team/graph'],
  ['POST', '/api/team/lifecycle'],
  ['POST', '/api/team/manual-materialize-and-create'],
  ['POST', '/api/team/public'],
  ['POST', '/api/team/skill'],
  ['POST', '/api/team/task-board'],
  ['POST', '/api/team/trigger'],
  ['GET', '/api/runtime-host/team-webhook-auth'],
  ['GET', '/api/toolchain/uv/check'],
  ['POST', '/api/toolchain/uv/prepare'],
  ['GET', '/api/remote-fleet/list-audit-events'],
  ['GET', '/api/remote-fleet/list-commands'],
  ['GET', '/api/remote-fleet/metrics'],
  ['GET', '/api/remote-fleet/snapshot'],
  ['GET', '/api/remote-fleet/terminal/sessions'],
  ['POST', '/api/remote-fleet/runtime-agent/ingress'],
  ['POST', '/api/remote-fleet/drain-endpoint'],
  ['POST', '/api/remote-fleet/install-agent'],
  ['POST', '/api/remote-fleet/probe'],
  ['POST', '/api/remote-fleet/probe-connection'],
  ['POST', '/api/remote-fleet/start-runtime'],
  ['POST', '/api/remote-fleet/stop-runtime'],
  ['POST', '/api/remote-fleet/sync-capabilities'],
  ['POST', '/api/remote-fleet/register-connection'],
  ['POST', '/api/remote-fleet/delete-connection'],
  ['POST', '/api/remote-fleet/register-environment'],
  ['POST', '/api/remote-fleet/deploy-environment'],
  ['POST', '/api/remote-fleet/delete-environment'],
  ['POST', '/api/remote-fleet/write-credential'],
  ['POST', '/api/remote-fleet/terminal/open'],
  ['POST', '/api/remote-fleet/terminal/reconnect'],
  ['POST', '/api/remote-fleet/terminal/close'],
  ['POST', '/api/remote-fleet/remove-node'],
  ['POST', '/api/remote-fleet/retire-endpoint'],
  ['POST', '/api/remote-fleet/revoke-agent'],
] as const);

const HOST_API_ALLOWED_DYNAMIC_REQUESTS = Object.freeze([
  ['GET', '/api/billing/orders/:orderId'],
  ['GET', '/api/channels/pairing/:channelType'],
  ['GET', '/api/openclaw/subagent-templates/:templateId'],
  ['GET', '/api/settings/:key'],
  ['GET', '/api/provider-accounts/:accountId/has-api-key'],
] as const satisfies readonly HostApiAllowedRequest[]);

export function getMainApiBoundarySnapshot() {
  return {
    allowedRouteFiles: [...MAIN_API_ALLOWED_ROUTE_FILES],
    hostapiProxyWebsocketExactRoutes: [...HOSTAPI_PROXY_WEBSOCKET_EXACT_ROUTES],
    mainOwnedExactRoutes: [...MAIN_OWNED_EXACT_ROUTES],
    hostApiAllowedRequests: HOST_API_ALLOWED_REQUESTS.map(([method, pathname]) => [method, pathname]),
    hostApiAllowedDynamicRequests: HOST_API_ALLOWED_DYNAMIC_REQUESTS.map(([method, pathname]) => [method, pathname]),
  };
}

export function isMainOwnedRoute(pathname: string): boolean {
  return MAIN_OWNED_EXACT_ROUTES.includes(pathname)
    || HOST_API_ALLOWED_DYNAMIC_REQUESTS.some(([, template]) => isSafeDynamicRoute(pathname, template));
}

export function isHostApiQueryTokenAllowedRoute(method: string | undefined, pathname: string): boolean {
  return method?.toUpperCase() === 'GET' && pathname === '/api/events';
}

export function isHostApiProxyWebSocketRoute(pathname: string): boolean {
  return HOSTAPI_PROXY_WEBSOCKET_EXACT_ROUTES.includes(pathname);
}

export function isHostApiRequestAllowed(method: string, pathname: string): boolean {
  const normalizedMethod = method.toUpperCase();
  if (HOST_API_ALLOWED_REQUESTS.some(
    ([allowedMethod, allowedPathname]) =>
      allowedMethod === normalizedMethod && allowedPathname === pathname,
  )) {
    return true;
  }
  return HOST_API_ALLOWED_DYNAMIC_REQUESTS.some(
    ([allowedMethod, template]) =>
      allowedMethod === normalizedMethod && isSafeDynamicRoute(pathname, template),
  );
}

function isSafeDynamicRoute(pathname: string, template: string): boolean {
  const templateSegments = template.split('/');
  const pathnameSegments = pathname.split('/');
  if (pathnameSegments.length !== templateSegments.length) return false;

  for (let index = 0; index < templateSegments.length; index += 1) {
    const templateSegment = templateSegments[index];
    const pathnameSegment = pathnameSegments[index];
    if (templateSegment.startsWith(':')) {
      if (!isSafeDynamicSegment(pathnameSegment)) return false;
    } else if (templateSegment !== pathnameSegment) {
      return false;
    }
  }
  return true;
}

function isSafeDynamicSegment(segment: string | undefined): boolean {
  if (!segment) return false;
  let decodedSegment: string;
  try {
    decodedSegment = decodeURIComponent(segment);
  } catch {
    return false;
  }
  return decodedSegment.length > 0
    && decodedSegment !== '.'
    && decodedSegment !== '..'
    && !decodedSegment.includes('/')
    && !decodedSegment.includes('\\')
    && !decodedSegment.includes('\0');
}
