export const CHAT_LAYOUT_TOKENS = {
  threadViewportPadding: 'px-3 py-3 sm:px-4 md:px-5 lg:px-6',
  threadRail: 'w-full',
  threadEmptyStateRail: 'mx-auto flex min-h-full max-w-5xl items-start justify-center',
  messageShell: 'group grid items-start gap-3 max-md:gap-2.5 max-sm:gap-2',
  messageShellAssistantColumns: 'grid-cols-[auto_minmax(0,1fr)]',
  messageShellUserColumns: 'grid-cols-[minmax(0,1fr)_auto]',
  messageAvatar: 'mt-1 flex h-8 w-8 shrink-0 self-start items-center justify-center rounded-full max-md:h-7 max-md:w-7 max-[400px]:hidden',
  messageAvatarAssistantOrder: 'order-1',
  messageAvatarUserOrder: 'order-2',
  messageContentColumn: 'flex min-w-0 flex-col space-y-2 max-w-[min(900px,68%)] max-xl:max-w-[76%] max-md:max-w-[88%] max-sm:max-w-[92%] max-[400px]:max-w-full',
  messageContentAssistantOrder: 'order-2 justify-self-start items-start',
  messageContentUserOrder: 'order-1 justify-self-end items-end',
  userBubble: 'relative rounded-2xl border border-border/60 bg-secondary px-4 py-3 text-foreground dark:border-border/70 dark:bg-secondary/85 max-md:rounded-xl max-md:px-3 max-md:py-2.5 max-sm:px-3 max-sm:py-2',
  inputRail: 'w-full min-w-0',
  inputCard: 'w-full min-w-0 rounded-[1.75rem] border border-input bg-card px-3 py-3 transition-[border-color,box-shadow,background-color] max-md:rounded-2xl max-md:px-2.5 max-md:py-2.5 max-sm:rounded-xl max-sm:px-2 max-sm:py-2',
  inputCardHeroMinHeight: 'min-h-[96px] max-md:min-h-[84px] max-sm:min-h-[72px]',
  inputCardDockMinHeight: 'min-h-[72px] max-md:min-h-[64px] max-sm:min-h-[56px]',
  inputTextarea: 'min-h-[44px] max-h-[200px] resize-none border-0 bg-transparent pl-1 pr-2 text-sm shadow-none focus-visible:ring-0 focus-visible:ring-offset-0 max-md:min-h-[40px] max-sm:text-[13px]',
  inputTextareaHeroMinHeight: 'min-h-[72px] max-md:min-h-[60px] max-sm:min-h-[52px]',
  inputActionsRow: 'mt-2 flex items-center justify-between gap-3 px-2 max-sm:mt-1.5 max-sm:px-1',
  inputAttachButton: 'h-10 w-10 shrink-0 max-sm:h-9 max-sm:w-9',
  inputSendButton: 'h-11 w-11 shrink-0 max-sm:h-10 max-sm:w-10',
  runtimeDockRail: 'mx-auto w-full max-w-4xl',
} as const;
