export const PROVIDER_VENDOR_DEFINITIONS = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🤖',
    placeholder: 'sk-ant-api03-...',
    model: 'Claude',
    requiresApiKey: true,
    category: 'official',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModelId: 'claude-opus-4-6',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '💚',
    placeholder: 'sk-proj-...',
    model: 'GPT',
    requiresApiKey: true,
    category: 'official',
    envVar: 'OPENAI_API_KEY',
    defaultModelId: 'gpt-5.4',
    isOAuth: true,
    supportsApiKey: true,
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'gpt-5.4',
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  {
    id: 'google',
    name: 'Google',
    icon: '🔷',
    placeholder: 'AIza...',
    model: 'Gemini',
    requiresApiKey: true,
    category: 'official',
    envVar: 'GEMINI_API_KEY',
    defaultModelId: 'gemini-3-pro-preview',
    isOAuth: true,
    supportsApiKey: true,
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'gemini-3-pro-preview',
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🌐',
    placeholder: 'sk-or-v1-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    showModelId: true,
    modelIdPlaceholder: 'anthropic/claude-opus-4.6',
    defaultModelId: 'anthropic/claude-opus-4.6',
    category: 'compatible',
    envVar: 'OPENROUTER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
  },
  {
    id: 'ark',
    name: 'ByteDance Ark',
    icon: 'A',
    placeholder: 'your-ark-api-key',
    model: 'Doubao',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'ep-20260228000000-xxxxx',
    category: 'official',
    envVar: 'ARK_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'moonshot',
    name: 'Moonshot (CN)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    defaultModelId: 'kimi-k2.5',
    category: 'official',
    envVar: 'MOONSHOT_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (CN)',
    icon: '🌊',
    placeholder: 'sk-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'deepseek-ai/DeepSeek-V3',
    defaultModelId: 'deepseek-ai/DeepSeek-V3',
    category: 'compatible',
    envVar: 'SILICONFLOW_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'minimax-portal',
    name: 'MiniMax (Global)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.7',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'MiniMax-M2.7',
    apiKeyUrl: 'https://platform.minimax.io',
    category: 'official',
    envVar: 'MINIMAX_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
  },
  {
    id: 'minimax-portal-cn',
    name: 'MiniMax (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.7',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'MiniMax-M2.7',
    apiKeyUrl: 'https://platform.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_CN_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
  },
  {
    id: 'qwen-portal',
    name: 'Qwen',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: false,
    isOAuth: true,
    defaultModelId: 'coder-model',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'coder-model',
    category: 'official',
    envVar: 'QWEN_API_KEY',
    supportedAuthModes: ['oauth_device'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    placeholder: 'Not required',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:11434/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'qwen3:latest',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: '⚙️',
    placeholder: 'API key...',
    requiresApiKey: true,
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'your-provider/model-id',
    category: 'custom',
    envVar: 'CUSTOM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
];
