export const SETTINGS_DEFAULTS = {
  theme: 'system',
  language: 'en',
  userAvatarDataUrl: null,
  startMinimized: false,
  launchAtStartup: false,
  telemetryEnabled: true,
  gatewayAutoStart: true,
  gatewayPort: 18789,
  gatewayToken: '',
  proxyEnabled: false,
  proxyServer: '',
  proxyBypassRules: '<local>;localhost;127.0.0.1;::1',
  clawHubToken: '',
  updateChannel: 'stable',
  autoCheckUpdate: true,
  autoDownloadUpdate: false,
  skippedVersions: [],
  sidebarCollapsed: false,
  devModeUnlocked: false,
  setupComplete: false,
  selectedBundles: ['productivity', 'developer'],
  enabledSkills: [],
  disabledSkills: [],
  pluginExecutionEnabled: true,
  pluginEnabledIds: [],
  securityPreset: 'balanced',
  securityPolicyVersion: 1,
  securityPolicyByAgent: {},
};

