[package]
name = "platform-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
foundation = { version = "0.1.0", path = "../../foundation" }
platform = { version = "0.1.0", path = "../../platform" }
runtime-directory = { version = "0.1.0", path = "../runtime-directory" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
