import type { AgentsTransport } from '../products/agents';
import type { SettingsDesiredTransport } from '../products/settings/desired';
import type { ChannelAuthorizationTransport } from './channels/authorization';
import type { ChannelCatalogTransport } from './channels/catalog';
import type { ChannelConfigReadTransport } from './channels/config-read';
import type { ChannelCredentialsTransport } from './channels/credentials';
import type { ChannelControlTransport } from './channels/control';
import type { ChannelDeleteConfigTransport } from './channels/delete-config';
import type { ChannelLoginTransport } from './channels/login';
import type { ChannelPairingTransport } from './channels/pairing';
import type { ChannelStatusTransport } from './channels/status';
import type { ExternalConnectorsTransport } from './connectors/external';
import type { OpenClawMcpServersTransport } from './connectors/openclaw-mcp-servers';
import type { CronTransport } from './cron';
import type { DiagnosticsArchiveTransport } from './diagnostics';
import type { FleetTransport } from './fleet';
import type { PluginsTransport } from './plugins';
import type { ProviderAccountsTransport } from './providers/accounts';
import type { ProviderModelsTransport } from './providers/models';
import type { ProviderRoutingTransport } from './providers/routing';
import type { RuntimeEndpointDirectoryTransport } from './runtime-directory';
import type { SecurityEmergencyTransport } from './security/emergency';
import type { SecurityPolicyTransport } from './security/policy';
import type { SecurityRuleCatalogTransport } from './security/rule-catalog';
import type { SessionAbortTransport } from './sessions/abort';
import type { SessionApprovalTransport } from './sessions/approvals';
import type { SessionContentTransport } from './sessions/content';
import type { SessionCreateTransport } from './sessions/create';
import type { SessionDeleteTransport } from './sessions/delete';
import type { MatchaAgentHistoryTransport } from './sessions/matcha-history';
import type { MatchaSessionListTransport } from './sessions/matcha-list';
import type { SessionListTransport } from './sessions/list';
import type { SessionModelSelectionTransport } from './sessions/model-selection';
import type { SessionPermissionTransport } from './sessions/permission';
import type { SessionRenameTransport } from './sessions/rename';
import type { SessionSendTransport } from './sessions/send';
import type { SessionTimelineTransport } from './sessions/timeline';
import type { SkillBundleTransport } from './skills/bundle';
import type { ClawHubSkillInstallTransport } from './skills/clawhub-install';
import type { ClawHubSkillSearchTransport } from './skills/clawhub-search';
import type { SkillsManagementTransport } from './skills/management';
import type { SealedSkillsTransport } from './skills/sealed';
import type { TaskManagerTransport } from './task-manager';
import type { TeamApprovalsTransport } from './teams/approvals';
import type { TeamHumanDecisionTransport } from './teams/decision';
import type { TeamGraphTransport } from './teams/graph';
import type { TeamLifecycleTransport } from './teams/lifecycle';
import type { ManualTeamTransport } from './teams/manual';
import type { TeamPublicTransport } from './teams/public';
import type { TeamRoleChatTransport } from './teams/role-chat';
import type { TeamRoleSessionsTransport } from './teams/role-sessions';
import type { TeamSkillTransport } from './teams/skill';
import type { TeamTaskBoardTransport } from './teams/task-board';
import type { TeamTriggerTransport } from './teams/trigger';
import type { TeamWebhookAuthTransport } from './teams/webhook-auth';
import type { UsageTransport } from './usage';
import type { WorkspaceMediaTransport } from './workspace/media';
import type { WorkspaceBinaryTransport } from './workspace/read-binary';
import type { WorkspaceDirectoryTransport } from './workspace/read-directory';
import type { WorkspaceTextTransport } from './workspace/read-text';
import type { WorkspaceWriteTransport } from './workspace/write-text';

export interface RuntimeHostTransports {
  sessionListTransport: SessionListTransport;
  fleetTransport: FleetTransport;
  sessionTimelineTransport: SessionTimelineTransport;
  sessionContentTransport: SessionContentTransport;
  matchaSessionListTransport: MatchaSessionListTransport;
  sessionAbortTransport: SessionAbortTransport;
  sessionCreateTransport: SessionCreateTransport;
  sessionDeleteTransport: SessionDeleteTransport;
  sessionRenameTransport: SessionRenameTransport;
  sessionApprovalTransport: SessionApprovalTransport;
  diagnosticsArchiveTransport: DiagnosticsArchiveTransport;
  workspaceTextTransport: WorkspaceTextTransport;
  workspaceBinaryTransport: WorkspaceBinaryTransport;
  workspaceDirectoryTransport: WorkspaceDirectoryTransport;
  workspaceWriteTransport: WorkspaceWriteTransport;
  workspaceMediaTransport: WorkspaceMediaTransport;
  sessionSendTransport: SessionSendTransport;
  sessionModelSelectionTransport: SessionModelSelectionTransport;
  sessionPermissionTransport: SessionPermissionTransport;
  securityEmergencyTransport: SecurityEmergencyTransport;
  channelStatusTransport: ChannelStatusTransport;
  channelAuthorizationTransport: ChannelAuthorizationTransport;
  channelCatalogTransport: ChannelCatalogTransport;
  channelConfigReadTransport: ChannelConfigReadTransport;
  channelCredentialsTransport: ChannelCredentialsTransport;
  channelDeleteConfigTransport: ChannelDeleteConfigTransport;
  channelLoginTransport: ChannelLoginTransport;
  channelControlTransport: ChannelControlTransport;
  channelPairingTransport: ChannelPairingTransport;
  settingsDesiredTransport: SettingsDesiredTransport;
  securityPolicyTransport: SecurityPolicyTransport;
  securityRuleCatalogTransport: SecurityRuleCatalogTransport;
  cronTransport: CronTransport;
  taskManagerTransport: TaskManagerTransport;
  agentsTransport: AgentsTransport;
  teamPublicTransport: TeamPublicTransport;
  teamTaskBoardTransport: TeamTaskBoardTransport;
  teamRoleSessionsTransport: TeamRoleSessionsTransport;
  teamApprovalsTransport: TeamApprovalsTransport;
  teamGraphTransport: TeamGraphTransport;
  teamSkillTransport: TeamSkillTransport;
  teamTriggerTransport: TeamTriggerTransport;
  teamWebhookAuthTransport: TeamWebhookAuthTransport;
  teamLifecycleTransport: TeamLifecycleTransport;
  manualTeamTransport: ManualTeamTransport;
  teamHumanDecisionTransport: TeamHumanDecisionTransport;
  teamRoleChatTransport: TeamRoleChatTransport;
  providerAccountsTransport: ProviderAccountsTransport;
  providerModelsTransport: ProviderModelsTransport;
  externalConnectorsTransport: ExternalConnectorsTransport;
  openClawMcpServersTransport: OpenClawMcpServersTransport;
  providerRoutingTransport: ProviderRoutingTransport;
  clawHubSkillInstallTransport: ClawHubSkillInstallTransport;
  clawHubSkillSearchTransport: ClawHubSkillSearchTransport;
  skillBundleTransport: SkillBundleTransport;
  skillsManagementTransport: SkillsManagementTransport;
  sealedSkillsTransport: SealedSkillsTransport;
  pluginsTransport: PluginsTransport;
  matchaAgentHistoryTransport: MatchaAgentHistoryTransport;
  usageTransport: UsageTransport;
  runtimeDirectoryTransport: RuntimeEndpointDirectoryTransport;
}
